---
title: "Details"
toc: false
---

Some helpful details as you plan your trip.

## Getting there

There are several transportation options for getting to Burlington.

* Air: The Burlington airport (BTV) is 2 miles from downtown Burlington and there is a [bus](https://ridegmt.com/11-airport/) from the airport to downtown Burlington.
* Rail: The Amtrak [Vermonter](https://www.amtrak.com/vermonter-train) runs from Washington D.C. and Philadelphia to Essex Junction which is a 10 minute drive from Burlington (via the [bus](https://ridegmt.com/2-essex-2/) or a ride sharing service). The Amtrak [Ethan Allen Express](https://www.amtrak.com/ethan-allen-express-train) runs from NYC to downtown Burlington.
* Bus: There are direct [Greyhound](https://www.greyhound.com/) and [megabus](https://us.megabus.com/route-guides/burlington-to-boston-bus) trips from Boston to Burlington.

# Accommodations

We have negotiated a lower rate with one of the local hotels. Let us know if you are interested in booking this option and we will provide you with more details.